version: "3.1"

services:
  api:
    restart: always
    ports:
      - 5001:5001
    environment:
      HOST: "0.0.0.0"
      PORT: 5001
      SOCKET_ADDRESS: "tcp://service:5555"
    build:
      context: ./api/
      dockerfile: Dockerfile
  service:
    restart: always
    build:
      context: ./manager
      dockerfile: Dockerfile
    ports:
      - 5555:5555
      - 5556:5556
  trainer:
    restart: always
    ports:
      - 5002:5002
    environment:
      HOST: "0.0.0.0"
      PORT: 5002
    build:
      context: ./trainer
      dockerfile: Dockerfile
